export type CareerStep = {
  id: string
  title: string
  description: string
  salaryRange?: string
  companies?: string[]
  icon?: string
}

export type CareerBranch = {
  id: string
  name: string
  description: string
  steps: CareerStep[]
}

export type CareerPath = {
  majorId: string
  majorName: string
  description: string
  branches: CareerBranch[]
}

export const careerPaths: CareerPath[] = [
  {
    majorId: "finance",
    majorName: "Finance",
    description: "Explore various career paths in the finance industry, from investment banking to corporate finance.",
    branches: [
      {
        id: "investment-banking",
        name: "Investment Banking Path",
        description: "A high-intensity career path focused on capital markets, M&A, and financial advisory.",
        steps: [
          {
            id: "pre-business",
            title: "Pre-Business Courses",
            description: "Complete foundational business courses with focus on economics, accounting, and statistics.",
            icon: "BookOpen",
          },
          {
            id: "finance-core",
            title: "Finance Core Curriculum",
            description: "Master financial modeling, valuation techniques, and investment analysis.",
            icon: "Calculator",
          },
          {
            id: "ib-internship",
            title: "Investment Banking Internship",
            description: "Summer analyst role at an investment bank, working on financial models and deal support.",
            salaryRange: "$15,000 - $25,000 (Summer)",
            companies: ["Goldman Sachs", "JP Morgan", "Morgan Stanley", "Credit Suisse"],
            icon: "Building",
          },
          {
            id: "ib-analyst",
            title: "Investment Banking Analyst",
            description:
              "Entry-level position analyzing financial data, creating models, and supporting deal execution.",
            salaryRange: "$85,000 - $120,000",
            companies: ["Goldman Sachs", "JP Morgan", "Morgan Stanley", "Barclays"],
            icon: "TrendingUp",
          },
          {
            id: "ib-associate",
            title: "Investment Banking Associate",
            description: "Mid-level banker managing analysts and having more client interaction.",
            salaryRange: "$150,000 - $250,000",
            companies: ["Goldman Sachs", "JP Morgan", "Morgan Stanley", "Bank of America"],
            icon: "Users",
          },
          {
            id: "ib-vp",
            title: "Vice President",
            description: "Senior banker responsible for client relationships and deal origination.",
            salaryRange: "$250,000 - $500,000",
            companies: ["Goldman Sachs", "JP Morgan", "Morgan Stanley", "Deutsche Bank"],
            icon: "Award",
          },
        ],
      },
      {
        id: "corporate-finance",
        name: "Corporate Finance Path",
        description: "A balanced career path focused on financial management within corporations.",
        steps: [
          {
            id: "pre-business",
            title: "Pre-Business Courses",
            description: "Complete foundational business courses with focus on economics, accounting, and statistics.",
            icon: "BookOpen",
          },
          {
            id: "finance-core",
            title: "Finance Core Curriculum",
            description: "Master financial analysis, corporate finance, and financial statement analysis.",
            icon: "Calculator",
          },
          {
            id: "corp-internship",
            title: "Corporate Finance Internship",
            description: "Finance intern role at a corporation, supporting financial planning and analysis.",
            salaryRange: "$12,000 - $20,000 (Summer)",
            companies: ["Microsoft", "Amazon", "Procter & Gamble", "Johnson & Johnson"],
            icon: "Building",
          },
          {
            id: "financial-analyst",
            title: "Financial Analyst",
            description: "Entry-level position analyzing financial data and supporting business decisions.",
            salaryRange: "$65,000 - $85,000",
            companies: ["Microsoft", "Amazon", "Apple", "Google"],
            icon: "PieChart",
          },
          {
            id: "senior-analyst",
            title: "Senior Financial Analyst",
            description: "Experienced analyst leading financial planning and analysis projects.",
            salaryRange: "$85,000 - $110,000",
            companies: ["Microsoft", "Amazon", "Apple", "Google"],
            icon: "TrendingUp",
          },
          {
            id: "finance-manager",
            title: "Finance Manager",
            description: "Manager overseeing financial operations and a team of analysts.",
            salaryRange: "$110,000 - $150,000",
            companies: ["Microsoft", "Amazon", "Apple", "Google"],
            icon: "Users",
          },
          {
            id: "finance-director",
            title: "Finance Director",
            description: "Senior leader responsible for financial strategy and operations.",
            salaryRange: "$150,000 - $250,000",
            companies: ["Microsoft", "Amazon", "Apple", "Google"],
            icon: "Award",
          },
        ],
      },
      {
        id: "wealth-management",
        name: "Wealth Management Path",
        description: "A client-focused career path helping individuals and families manage their investments.",
        steps: [
          {
            id: "pre-business",
            title: "Pre-Business Courses",
            description: "Complete foundational business courses with focus on economics, accounting, and statistics.",
            icon: "BookOpen",
          },
          {
            id: "finance-core",
            title: "Finance Core Curriculum",
            description: "Master investment principles, portfolio management, and financial planning.",
            icon: "Calculator",
          },
          {
            id: "wm-internship",
            title: "Wealth Management Internship",
            description: "Intern supporting financial advisors and learning client relationship management.",
            salaryRange: "$10,000 - $18,000 (Summer)",
            companies: ["Merrill Lynch", "UBS", "Morgan Stanley Wealth Management", "Charles Schwab"],
            icon: "Building",
          },
          {
            id: "financial-advisor",
            title: "Financial Advisor",
            description: "Entry-level advisor building client relationships and creating financial plans.",
            salaryRange: "$60,000 - $80,000",
            companies: ["Merrill Lynch", "UBS", "Edward Jones", "Fidelity"],
            icon: "Users",
          },
          {
            id: "senior-advisor",
            title: "Senior Financial Advisor",
            description: "Experienced advisor managing significant client assets and complex financial situations.",
            salaryRange: "$100,000 - $200,000",
            companies: ["Merrill Lynch", "UBS", "Morgan Stanley Wealth Management", "Wells Fargo Advisors"],
            icon: "TrendingUp",
          },
          {
            id: "wealth-director",
            title: "Wealth Management Director",
            description: "Senior leader overseeing a team of advisors and managing high-net-worth clients.",
            salaryRange: "$200,000 - $500,000+",
            companies: ["Merrill Lynch", "UBS", "Morgan Stanley Wealth Management", "Goldman Sachs Private Wealth"],
            icon: "Award",
          },
        ],
      },
    ],
  },
  {
    majorId: "accounting",
    majorName: "Accounting",
    description: "Explore various career paths in accounting, from public accounting to corporate roles.",
    branches: [
      {
        id: "public-accounting",
        name: "Public Accounting Path",
        description: "A career path focused on auditing, tax, and advisory services for clients.",
        steps: [
          {
            id: "pre-business",
            title: "Pre-Business Courses",
            description: "Complete foundational business courses with focus on accounting principles and economics.",
            icon: "BookOpen",
          },
          {
            id: "accounting-core",
            title: "Accounting Core Curriculum",
            description: "Master financial accounting, auditing, tax, and accounting information systems.",
            icon: "Calculator",
          },
          {
            id: "public-internship",
            title: "Public Accounting Internship",
            description: "Intern at a public accounting firm, supporting audit or tax engagements.",
            salaryRange: "$12,000 - $20,000 (Winter/Summer)",
            companies: ["Deloitte", "PwC", "EY", "KPMG"],
            icon: "Building",
          },
          {
            id: "audit-associate",
            title: "Audit Associate",
            description: "Entry-level position conducting financial statement audits for clients.",
            salaryRange: "$60,000 - $75,000",
            companies: ["Deloitte", "PwC", "EY", "KPMG"],
            icon: "Search",
          },
          {
            id: "audit-senior",
            title: "Audit Senior",
            description: "Experienced auditor leading audit engagements and supervising associates.",
            salaryRange: "$75,000 - $95,000",
            companies: ["Deloitte", "PwC", "EY", "KPMG"],
            icon: "Users",
          },
          {
            id: "audit-manager",
            title: "Audit Manager",
            description: "Manager overseeing multiple audit engagements and client relationships.",
            salaryRange: "$95,000 - $130,000",
            companies: ["Deloitte", "PwC", "EY", "KPMG"],
            icon: "Briefcase",
          },
          {
            id: "audit-partner",
            title: "Audit Partner",
            description: "Senior leader responsible for client relationships and firm management.",
            salaryRange: "$300,000 - $1,000,000+",
            companies: ["Deloitte", "PwC", "EY", "KPMG"],
            icon: "Award",
          },
        ],
      },
      {
        id: "corporate-accounting",
        name: "Corporate Accounting Path",
        description: "A career path focused on accounting within corporations.",
        steps: [
          {
            id: "pre-business",
            title: "Pre-Business Courses",
            description: "Complete foundational business courses with focus on accounting principles and economics.",
            icon: "BookOpen",
          },
          {
            id: "accounting-core",
            title: "Accounting Core Curriculum",
            description: "Master financial accounting, managerial accounting, and accounting information systems.",
            icon: "Calculator",
          },
          {
            id: "corporate-internship",
            title: "Corporate Accounting Internship",
            description: "Intern in a corporate accounting department, supporting financial reporting or analysis.",
            salaryRange: "$10,000 - $18,000 (Summer)",
            companies: ["Microsoft", "Amazon", "Procter & Gamble", "Johnson & Johnson"],
            icon: "Building",
          },
          {
            id: "staff-accountant",
            title: "Staff Accountant",
            description: "Entry-level position supporting financial reporting and accounting operations.",
            salaryRange: "$55,000 - $70,000",
            companies: ["Microsoft", "Amazon", "Apple", "Google"],
            icon: "FileText",
          },
          {
            id: "senior-accountant",
            title: "Senior Accountant",
            description: "Experienced accountant managing specific accounting functions.",
            salaryRange: "$70,000 - $90,000",
            companies: ["Microsoft", "Amazon", "Apple", "Google"],
            icon: "TrendingUp",
          },
          {
            id: "accounting-manager",
            title: "Accounting Manager",
            description: "Manager overseeing accounting operations and a team of accountants.",
            salaryRange: "$90,000 - $120,000",
            companies: ["Microsoft", "Amazon", "Apple", "Google"],
            icon: "Users",
          },
          {
            id: "controller",
            title: "Controller",
            description: "Senior leader responsible for all accounting operations and financial reporting.",
            salaryRange: "$120,000 - $200,000",
            companies: ["Microsoft", "Amazon", "Apple", "Google"],
            icon: "Award",
          },
          {
            id: "cfo",
            title: "Chief Financial Officer",
            description: "Executive responsible for all financial aspects of the company.",
            salaryRange: "$200,000 - $1,000,000+",
            companies: ["Microsoft", "Amazon", "Apple", "Google"],
            icon: "Star",
          },
        ],
      },
    ],
  },
  {
    majorId: "marketing",
    majorName: "Marketing",
    description: "Explore various career paths in marketing, from brand management to digital marketing.",
    branches: [
      {
        id: "brand-management",
        name: "Brand Management Path",
        description: "A career path focused on developing and managing consumer brands.",
        steps: [
          {
            id: "pre-business",
            title: "Pre-Business Courses",
            description:
              "Complete foundational business courses with focus on marketing principles and consumer behavior.",
            icon: "BookOpen",
          },
          {
            id: "marketing-core",
            title: "Marketing Core Curriculum",
            description: "Master marketing strategy, consumer behavior, and market research.",
            icon: "BookOpen",
          },
          {
            id: "brand-internship",
            title: "Brand Management Internship",
            description: "Intern supporting brand managers on marketing campaigns and product launches.",
            salaryRange: "$12,000 - $20,000 (Summer)",
            companies: ["Procter & Gamble", "Unilever", "Coca-Cola", "PepsiCo"],
            icon: "Building",
          },
          {
            id: "assistant-brand-manager",
            title: "Assistant Brand Manager",
            description: "Entry-level position supporting brand strategy and marketing campaigns.",
            salaryRange: "$60,000 - $80,000",
            companies: ["Procter & Gamble", "Unilever", "Coca-Cola", "PepsiCo"],
            icon: "Briefcase",
          },
          {
            id: "brand-manager",
            title: "Brand Manager",
            description: "Manager responsible for brand strategy, marketing campaigns, and product development.",
            salaryRange: "$80,000 - $120,000",
            companies: ["Procter & Gamble", "Unilever", "Coca-Cola", "PepsiCo"],
            icon: "Users",
          },
          {
            id: "senior-brand-manager",
            title: "Senior Brand Manager",
            description: "Senior manager overseeing multiple brands or a major brand portfolio.",
            salaryRange: "$120,000 - $180,000",
            companies: ["Procter & Gamble", "Unilever", "Coca-Cola", "PepsiCo"],
            icon: "TrendingUp",
          },
          {
            id: "marketing-director",
            title: "Marketing Director",
            description: "Director responsible for marketing strategy across multiple brands or categories.",
            salaryRange: "$180,000 - $250,000",
            companies: ["Procter & Gamble", "Unilever", "Coca-Cola", "PepsiCo"],
            icon: "Award",
          },
          {
            id: "cmo",
            title: "Chief Marketing Officer",
            description: "Executive responsible for all marketing activities of the company.",
            salaryRange: "$250,000 - $1,000,000+",
            companies: ["Procter & Gamble", "Unilever", "Coca-Cola", "PepsiCo"],
            icon: "Star",
          },
        ],
      },
      {
        id: "digital-marketing",
        name: "Digital Marketing Path",
        description: "A career path focused on digital marketing channels and strategies.",
        steps: [
          {
            id: "pre-business",
            title: "Pre-Business Courses",
            description: "Complete foundational business courses with focus on marketing principles and analytics.",
            icon: "BookOpen",
          },
          {
            id: "marketing-core",
            title: "Marketing Core Curriculum",
            description: "Master digital marketing, social media strategy, and marketing analytics.",
            icon: "BookOpen",
          },
          {
            id: "digital-internship",
            title: "Digital Marketing Internship",
            description: "Intern supporting digital marketing campaigns and social media management.",
            salaryRange: "$10,000 - $18,000 (Summer)",
            companies: ["Google", "Meta", "Amazon", "HubSpot"],
            icon: "Building",
          },
          {
            id: "digital-specialist",
            title: "Digital Marketing Specialist",
            description: "Entry-level position managing digital marketing campaigns and social media.",
            salaryRange: "$55,000 - $75,000",
            companies: ["Google", "Meta", "Amazon", "HubSpot"],
            icon: "Monitor",
          },
          {
            id: "digital-manager",
            title: "Digital Marketing Manager",
            description: "Manager responsible for digital marketing strategy and campaigns.",
            salaryRange: "$75,000 - $110,000",
            companies: ["Google", "Meta", "Amazon", "HubSpot"],
            icon: "Users",
          },
          {
            id: "digital-director",
            title: "Digital Marketing Director",
            description: "Director overseeing all digital marketing channels and strategies.",
            salaryRange: "$110,000 - $180,000",
            companies: ["Google", "Meta", "Amazon", "HubSpot"],
            icon: "TrendingUp",
          },
          {
            id: "vp-digital",
            title: "VP of Digital Marketing",
            description: "Senior leader responsible for digital transformation and marketing innovation.",
            salaryRange: "$180,000 - $300,000",
            companies: ["Google", "Meta", "Amazon", "HubSpot"],
            icon: "Award",
          },
        ],
      },
    ],
  },
  {
    majorId: "information-systems",
    majorName: "Information Systems",
    description: "Explore various career paths in information systems, from software development to IT consulting.",
    branches: [
      {
        id: "software-development",
        name: "Software Development Path",
        description: "A career path focused on building and maintaining software applications.",
        steps: [
          {
            id: "pre-business",
            title: "Pre-Business Courses",
            description: "Complete foundational business courses with focus on programming and database concepts.",
            icon: "BookOpen",
          },
          {
            id: "is-core",
            title: "Information Systems Core",
            description: "Master programming, database design, and systems analysis.",
            icon: "BookOpen",
          },
          {
            id: "dev-internship",
            title: "Software Development Internship",
            description: "Intern supporting software development projects and learning coding practices.",
            salaryRange: "$15,000 - $25,000 (Summer)",
            companies: ["Microsoft", "Amazon", "Google", "Adobe"],
            icon: "Building",
          },
          {
            id: "junior-developer",
            title: "Junior Developer",
            description: "Entry-level position writing code and supporting software applications.",
            salaryRange: "$70,000 - $90,000",
            companies: ["Microsoft", "Amazon", "Google", "Adobe"],
            icon: "Code",
          },
          {
            id: "developer",
            title: "Software Developer",
            description: "Experienced developer building and maintaining software applications.",
            salaryRange: "$90,000 - $120,000",
            companies: ["Microsoft", "Amazon", "Google", "Adobe"],
            icon: "Terminal",
          },
          {
            id: "senior-developer",
            title: "Senior Developer",
            description: "Senior developer leading development projects and mentoring junior developers.",
            salaryRange: "$120,000 - $160,000",
            companies: ["Microsoft", "Amazon", "Google", "Adobe"],
            icon: "Users",
          },
          {
            id: "tech-lead",
            title: "Technical Lead",
            description: "Lead responsible for technical architecture and development team leadership.",
            salaryRange: "$160,000 - $200,000",
            companies: ["Microsoft", "Amazon", "Google", "Adobe"],
            icon: "Award",
          },
          {
            id: "cto",
            title: "Chief Technology Officer",
            description: "Executive responsible for technology strategy and innovation.",
            salaryRange: "$200,000 - $1,000,000+",
            companies: ["Microsoft", "Amazon", "Google", "Adobe"],
            icon: "Star",
          },
        ],
      },
      {
        id: "it-consulting",
        name: "IT Consulting Path",
        description: "A career path focused on helping organizations implement and optimize technology solutions.",
        steps: [
          {
            id: "pre-business",
            title: "Pre-Business Courses",
            description: "Complete foundational business courses with focus on business processes and technology.",
            icon: "BookOpen",
          },
          {
            id: "is-core",
            title: "Information Systems Core",
            description: "Master systems analysis, project management, and business process improvement.",
            icon: "BookOpen",
          },
          {
            id: "consulting-internship",
            title: "IT Consulting Internship",
            description: "Intern supporting consulting projects and client engagements.",
            salaryRange: "$12,000 - $22,000 (Summer)",
            companies: ["Deloitte", "Accenture", "IBM", "Capgemini"],
            icon: "Building",
          },
          {
            id: "analyst",
            title: "Technology Analyst",
            description: "Entry-level position supporting technology implementation projects.",
            salaryRange: "$65,000 - $85,000",
            companies: ["Deloitte", "Accenture", "IBM", "Capgemini"],
            icon: "Search",
          },
          {
            id: "consultant",
            title: "IT Consultant",
            description: "Consultant managing specific aspects of technology implementation projects.",
            salaryRange: "$85,000 - $110,000",
            companies: ["Deloitte", "Accenture", "IBM", "Capgemini"],
            icon: "Users",
          },
          {
            id: "senior-consultant",
            title: "Senior IT Consultant",
            description: "Senior consultant leading client engagements and project teams.",
            salaryRange: "$110,000 - $150,000",
            companies: ["Deloitte", "Accenture", "IBM", "Capgemini"],
            icon: "Briefcase",
          },
          {
            id: "manager",
            title: "Consulting Manager",
            description: "Manager responsible for client relationships and multiple project teams.",
            salaryRange: "$150,000 - $200,000",
            companies: ["Deloitte", "Accenture", "IBM", "Capgemini"],
            icon: "TrendingUp",
          },
          {
            id: "partner",
            title: "Consulting Partner",
            description: "Senior leader responsible for practice growth and client relationships.",
            salaryRange: "$200,000 - $1,000,000+",
            companies: ["Deloitte", "Accenture", "IBM", "Capgemini"],
            icon: "Award",
          },
        ],
      },
    ],
  },
  {
    majorId: "strategy",
    majorName: "Strategy",
    description: "Explore various career paths in strategy, from management consulting to corporate strategy.",
    branches: [
      {
        id: "management-consulting",
        name: "Management Consulting Path",
        description: "A career path focused on helping organizations solve complex business problems.",
        steps: [
          {
            id: "pre-business",
            title: "Pre-Business Courses",
            description: "Complete foundational business courses with focus on economics, statistics, and analytics.",
            icon: "BookOpen",
          },
          {
            id: "strategy-core",
            title: "Strategy Core Curriculum",
            description: "Master strategic analysis, problem-solving, and business frameworks.",
            icon: "BookOpen",
          },
          {
            id: "consulting-internship",
            title: "Management Consulting Internship",
            description: "Intern supporting consulting projects and client engagements.",
            salaryRange: "$15,000 - $30,000 (Summer)",
            companies: ["McKinsey", "BCG", "Bain", "Deloitte"],
            icon: "Building",
          },
          {
            id: "business-analyst",
            title: "Business Analyst",
            description: "Entry-level position analyzing data and supporting client engagements.",
            salaryRange: "$80,000 - $100,000",
            companies: ["McKinsey", "BCG", "Bain", "Deloitte"],
            icon: "Search",
          },
          {
            id: "associate",
            title: "Associate Consultant",
            description: "Mid-level consultant leading workstreams and managing client relationships.",
            salaryRange: "$100,000 - $150,000",
            companies: ["McKinsey", "BCG", "Bain", "Deloitte"],
            icon: "Users",
          },
          {
            id: "manager",
            title: "Engagement Manager",
            description: "Manager responsible for client projects and team leadership.",
            salaryRange: "$150,000 - $200,000",
            companies: ["McKinsey", "BCG", "Bain", "Deloitte"],
            icon: "Briefcase",
          },
          {
            id: "principal",
            title: "Principal/Senior Manager",
            description: "Senior leader responsible for client relationships and practice development.",
            salaryRange: "$200,000 - $300,000",
            companies: ["McKinsey", "BCG", "Bain", "Deloitte"],
            icon: "TrendingUp",
          },
          {
            id: "partner",
            title: "Partner/Director",
            description: "Senior partner responsible for firm leadership and client relationships.",
            salaryRange: "$300,000 - $1,000,000+",
            companies: ["McKinsey", "BCG", "Bain", "Deloitte"],
            icon: "Award",
          },
        ],
      },
      {
        id: "corporate-strategy",
        name: "Corporate Strategy Path",
        description: "A career path focused on developing and implementing organizational strategy.",
        steps: [
          {
            id: "pre-business",
            title: "Pre-Business Courses",
            description: "Complete foundational business courses with focus on economics, statistics, and analytics.",
            icon: "BookOpen",
          },
          {
            id: "strategy-core",
            title: "Strategy Core Curriculum",
            description: "Master strategic planning, competitive analysis, and organizational behavior.",
            icon: "BookOpen",
          },
          {
            id: "strategy-internship",
            title: "Corporate Strategy Internship",
            description: "Intern supporting strategic initiatives and business development projects.",
            salaryRange: "$12,000 - $20,000 (Summer)",
            companies: ["Amazon", "Microsoft", "Google", "Apple"],
            icon: "Building",
          },
          {
            id: "strategy-analyst",
            title: "Strategy Analyst",
            description: "Entry-level position analyzing market trends and supporting strategic initiatives.",
            salaryRange: "$70,000 - $90,000",
            companies: ["Amazon", "Microsoft", "Google", "Apple"],
            icon: "Search",
          },
          {
            id: "senior-analyst",
            title: "Senior Strategy Analyst",
            description: "Experienced analyst leading strategic analysis and planning projects.",
            salaryRange: "$90,000 - $120,000",
            companies: ["Amazon", "Microsoft", "Google", "Apple"],
            icon: "TrendingUp",
          },
          {
            id: "strategy-manager",
            title: "Strategy Manager",
            description: "Manager responsible for strategic planning and implementation.",
            salaryRange: "$120,000 - $160,000",
            companies: ["Amazon", "Microsoft", "Google", "Apple"],
            icon: "Users",
          },
          {
            id: "director",
            title: "Director of Strategy",
            description: "Senior leader responsible for organizational strategy and strategic initiatives.",
            salaryRange: "$160,000 - $250,000",
            companies: ["Amazon", "Microsoft", "Google", "Apple"],
            icon: "Award",
          },
          {
            id: "chief-strategy",
            title: "Chief Strategy Officer",
            description: "Executive responsible for long-term strategic planning and corporate development.",
            salaryRange: "$250,000 - $800,000+",
            companies: ["Amazon", "Microsoft", "Google", "Apple"],
            icon: "Star",
          },
        ],
      },
      {
        id: "business-development",
        name: "Business Development Path",
        description: "A career path focused on growing businesses through partnerships and new opportunities.",
        steps: [
          {
            id: "pre-business",
            title: "Pre-Business Courses",
            description: "Complete foundational business courses with focus on economics, marketing, and strategy.",
            icon: "BookOpen",
          },
          {
            id: "strategy-core",
            title: "Strategy Core Curriculum",
            description: "Master strategic planning, business development, and negotiation.",
            icon: "BookOpen",
          },
          {
            id: "bd-internship",
            title: "Business Development Internship",
            description: "Intern supporting partnership development and growth initiatives.",
            salaryRange: "$10,000 - $18,000 (Summer)",
            companies: ["Salesforce", "Oracle", "Adobe", "Slack"],
            icon: "Building",
          },
          {
            id: "bd-associate",
            title: "Business Development Associate",
            description: "Entry-level position identifying and pursuing partnership opportunities.",
            salaryRange: "$65,000 - $85,000",
            companies: ["Salesforce", "Oracle", "Adobe", "Slack"],
            icon: "Briefcase",
          },
          {
            id: "bd-manager",
            title: "Business Development Manager",
            description: "Manager responsible for developing and managing strategic partnerships.",
            salaryRange: "$85,000 - $120,000",
            companies: ["Salesforce", "Oracle", "Adobe", "Slack"],
            icon: "Users",
          },
          {
            id: "senior-bd-manager",
            title: "Senior Business Development Manager",
            description: "Senior manager overseeing major partnerships and growth initiatives.",
            salaryRange: "$120,000 - $180,000",
            companies: ["Salesforce", "Oracle", "Adobe", "Slack"],
            icon: "TrendingUp",
          },
          {
            id: "bd-director",
            title: "Director of Business Development",
            description: "Director responsible for partnership strategy and business growth.",
            salaryRange: "$180,000 - $250,000",
            companies: ["Salesforce", "Oracle", "Adobe", "Slack"],
            icon: "Award",
          },
          {
            id: "vp-bd",
            title: "VP of Business Development",
            description: "Executive responsible for strategic partnerships and corporate development.",
            salaryRange: "$250,000 - $500,000+",
            companies: ["Salesforce", "Oracle", "Adobe", "Slack"],
            icon: "Star",
          },
        ],
      },
      {
        id: "product-management",
        name: "Product Management Path",
        description: "A career path focused on developing and managing products throughout their lifecycle.",
        steps: [
          {
            id: "pre-business",
            title: "Pre-Business Courses",
            description: "Complete foundational business courses with focus on strategy, marketing, and analytics.",
            icon: "BookOpen",
          },
          {
            id: "strategy-core",
            title: "Strategy Core Curriculum",
            description: "Master strategic planning, market analysis, and product development.",
            icon: "BookOpen",
          },
          {
            id: "product-internship",
            title: "Product Management Internship",
            description: "Intern supporting product development and go-to-market strategies.",
            salaryRange: "$12,000 - $25,000 (Summer)",
            companies: ["Google", "Microsoft", "Amazon", "Apple"],
            icon: "Building",
          },
          {
            id: "associate-pm",
            title: "Associate Product Manager",
            description: "Entry-level position supporting product development and feature prioritization.",
            salaryRange: "$70,000 - $95,000",
            companies: ["Google", "Microsoft", "Amazon", "Apple"],
            icon: "Package",
          },
          {
            id: "product-manager",
            title: "Product Manager",
            description: "Manager responsible for product strategy, roadmap, and feature development.",
            salaryRange: "$95,000 - $130,000",
            companies: ["Google", "Microsoft", "Amazon", "Apple"],
            icon: "Layers",
          },
          {
            id: "senior-pm",
            title: "Senior Product Manager",
            description: "Senior manager leading complex products and cross-functional teams.",
            salaryRange: "$130,000 - $180,000",
            companies: ["Google", "Microsoft", "Amazon", "Apple"],
            icon: "Users",
          },
          {
            id: "product-director",
            title: "Director of Product",
            description: "Director overseeing product lines and product management teams.",
            salaryRange: "$180,000 - $250,000",
            companies: ["Google", "Microsoft", "Amazon", "Apple"],
            icon: "TrendingUp",
          },
          {
            id: "vp-product",
            title: "VP of Product",
            description: "Executive responsible for product strategy and innovation across the organization.",
            salaryRange: "$250,000 - $500,000+",
            companies: ["Google", "Microsoft", "Amazon", "Apple"],
            icon: "Award",
          },
          {
            id: "chief-product",
            title: "Chief Product Officer",
            description: "C-level executive responsible for all product development and management.",
            salaryRange: "$350,000 - $1,000,000+",
            companies: ["Google", "Microsoft", "Amazon", "Apple"],
            icon: "Star",
          },
        ],
      },
    ],
  },
  {
    majorId: "entrepreneurship",
    majorName: "Entrepreneurship",
    description: "Explore various career paths in entrepreneurship, from startup founding to venture capital.",
    branches: [
      {
        id: "startup-founder",
        name: "Startup Founder Path",
        description: "A career path focused on launching and growing your own business venture.",
        steps: [
          {
            id: "pre-business",
            title: "Pre-Business Courses",
            description: "Complete foundational business courses with focus on entrepreneurship and innovation.",
            icon: "BookOpen",
          },
          {
            id: "entrepreneurship-core",
            title: "Entrepreneurship Core Curriculum",
            description: "Master business model development, venture financing, and startup management.",
            icon: "BookOpen",
          },
          {
            id: "startup-internship",
            title: "Startup Internship",
            description: "Intern at a startup to learn about early-stage business operations.",
            salaryRange: "$8,000 - $15,000 (Summer)",
            companies: ["Local Startups", "Tech Incubators", "Y Combinator Companies"],
            icon: "Building",
          },
          {
            id: "idea-validation",
            title: "Idea Validation & MVP",
            description: "Develop and validate your business idea, create a minimum viable product.",
            salaryRange: "Variable (Often unpaid)",
            companies: ["Self-employed", "Startup Accelerators", "Business Incubators"],
            icon: "Lightbulb",
          },
          {
            id: "seed-funding",
            title: "Seed Funding & Launch",
            description: "Secure initial funding and officially launch your business.",
            salaryRange: "$40,000 - $80,000 (Founder salary)",
            companies: ["Self-employed", "Angel Investors", "Seed Funds"],
            icon: "DollarSign",
          },
          {
            id: "growth-stage",
            title: "Growth Stage CEO",
            description: "Lead your company through growth phases and additional funding rounds.",
            salaryRange: "$80,000 - $150,000",
            companies: ["Self-employed", "Venture-backed Startups"],
            icon: "TrendingUp",
          },
          {
            id: "scale-stage",
            title: "Scale Stage CEO",
            description: "Scale your company to significant revenue and market presence.",
            salaryRange: "$150,000 - $300,000+",
            companies: ["Self-employed", "Venture-backed Companies"],
            icon: "Award",
          },
          {
            id: "exit-or-ipo",
            title: "Exit or IPO",
            description: "Lead your company to acquisition or public offering.",
            salaryRange: "Variable (Often millions upon exit)",
            companies: ["Public Companies", "Acquired Companies"],
            icon: "Star",
          },
        ],
      },
      {
        id: "corporate-innovation",
        name: "Corporate Innovation Path",
        description: "A career path focused on driving innovation within established companies.",
        steps: [
          {
            id: "pre-business",
            title: "Pre-Business Courses",
            description: "Complete foundational business courses with focus on innovation and business strategy.",
            icon: "BookOpen",
          },
          {
            id: "entrepreneurship-core",
            title: "Entrepreneurship Core Curriculum",
            description: "Master innovation management, design thinking, and corporate entrepreneurship.",
            icon: "BookOpen",
          },
          {
            id: "innovation-internship",
            title: "Corporate Innovation Internship",
            description: "Intern supporting innovation initiatives and new product development.",
            salaryRange: "$12,000 - $20,000 (Summer)",
            companies: ["Google", "Amazon", "Microsoft", "Apple"],
            icon: "Building",
          },
          {
            id: "innovation-analyst",
            title: "Innovation Analyst",
            description: "Entry-level position supporting innovation projects and initiatives.",
            salaryRange: "$65,000 - $85,000",
            companies: ["Google", "Amazon", "Microsoft", "Apple"],
            icon: "Search",
          },
          {
            id: "product-manager",
            title: "Product Manager",
            description: "Manager responsible for developing and launching new products or services.",
            salaryRange: "$85,000 - $120,000",
            companies: ["Google", "Amazon", "Microsoft", "Apple"],
            icon: "Package",
          },
          {
            id: "innovation-manager",
            title: "Innovation Manager",
            description: "Manager leading innovation programs and initiatives across the organization.",
            salaryRange: "$120,000 - $160,000",
            companies: ["Google", "Amazon", "Microsoft", "Apple"],
            icon: "Users",
          },
          {
            id: "innovation-director",
            title: "Director of Innovation",
            description: "Senior leader responsible for innovation strategy and new business development.",
            salaryRange: "$160,000 - $250,000",
            companies: ["Google", "Amazon", "Microsoft", "Apple"],
            icon: "Award",
          },
          {
            id: "chief-innovation",
            title: "Chief Innovation Officer",
            description: "Executive responsible for driving innovation and transformation across the organization.",
            salaryRange: "$250,000 - $800,000+",
            companies: ["Google", "Amazon", "Microsoft", "Apple"],
            icon: "Star",
          },
        ],
      },
      {
        id: "venture-capital",
        name: "Venture Capital Path",
        description: "A career path focused on investing in and supporting promising startups.",
        steps: [
          {
            id: "pre-business",
            title: "Pre-Business Courses",
            description: "Complete foundational business courses with focus on finance and entrepreneurship.",
            icon: "BookOpen",
          },
          {
            id: "entrepreneurship-core",
            title: "Entrepreneurship Core Curriculum",
            description: "Master venture financing, startup valuation, and business model analysis.",
            icon: "BookOpen",
          },
          {
            id: "vc-internship",
            title: "Venture Capital Internship",
            description: "Intern supporting deal sourcing, due diligence, and portfolio management.",
            salaryRange: "$12,000 - $25,000 (Summer)",
            companies: ["Sequoia Capital", "Andreessen Horowitz", "Kleiner Perkins", "Y Combinator"],
            icon: "Building",
          },
          {
            id: "vc-analyst",
            title: "Venture Capital Analyst",
            description: "Entry-level position sourcing deals and conducting market research.",
            salaryRange: "$80,000 - $120,000",
            companies: ["Sequoia Capital", "Andreessen Horowitz", "Kleiner Perkins", "First Round"],
            icon: "Search",
          },
          {
            id: "vc-associate",
            title: "Venture Capital Associate",
            description: "Associate evaluating investment opportunities and supporting portfolio companies.",
            salaryRange: "$120,000 - $180,000",
            companies: ["Sequoia Capital", "Andreessen Horowitz", "Kleiner Perkins", "First Round"],
            icon: "DollarSign",
          },
          {
            id: "principal",
            title: "Principal",
            description: "Senior investment professional leading deals and managing portfolio companies.",
            salaryRange: "$180,000 - $300,000",
            companies: ["Sequoia Capital", "Andreessen Horowitz", "Kleiner Perkins", "First Round"],
            icon: "TrendingUp",
          },
          {
            id: "partner",
            title: "Partner",
            description: "Partner responsible for investment decisions and fund management.",
            salaryRange: "$300,000 - $1,000,000+",
            companies: ["Sequoia Capital", "Andreessen Horowitz", "Kleiner Perkins", "First Round"],
            icon: "Award",
          },
          {
            id: "managing-partner",
            title: "Managing Partner",
            description: "Senior partner responsible for firm leadership and fund strategy.",
            salaryRange: "$1,000,000 - $10,000,000+",
            companies: ["Sequoia Capital", "Andreessen Horowitz", "Kleiner Perkins", "First Round"],
            icon: "Star",
          },
        ],
      },
    ],
  },
  {
    majorId: "global-supply-chain",
    majorName: "Global Supply Chain",
    description: "Explore various career paths in supply chain management, from logistics to procurement.",
    branches: [
      {
        id: "logistics-management",
        name: "Logistics Management Path",
        description: "A career path focused on managing the movement of goods through the supply chain.",
        steps: [
          {
            id: "pre-business",
            title: "Pre-Business Courses",
            description: "Complete foundational business courses with focus on operations and supply chain basics.",
            icon: "BookOpen",
          },
          {
            id: "supply-chain-core",
            title: "Supply Chain Core Curriculum",
            description: "Master logistics management, transportation systems, and distribution networks.",
            icon: "BookOpen",
          },
          {
            id: "logistics-internship",
            title: "Logistics Internship",
            description: "Intern supporting logistics operations and transportation management.",
            salaryRange: "$10,000 - $18,000 (Summer)",
            companies: ["Amazon", "UPS", "FedEx", "DHL"],
            icon: "Building",
          },
          {
            id: "logistics-coordinator",
            title: "Logistics Coordinator",
            description: "Entry-level position coordinating shipments and managing transportation.",
            salaryRange: "$50,000 - $65,000",
            companies: ["Amazon", "UPS", "FedEx", "DHL"],
            icon: "Truck",
          },
          {
            id: "logistics-analyst",
            title: "Logistics Analyst",
            description: "Analyst optimizing transportation networks and logistics operations.",
            salaryRange: "$65,000 - $85,000",
            companies: ["Amazon", "UPS", "FedEx", "DHL"],
            icon: "Search",
          },
          {
            id: "logistics-manager",
            title: "Logistics Manager",
            description: "Manager responsible for transportation operations and logistics strategy.",
            salaryRange: "$85,000 - $110,000",
            companies: ["Amazon", "UPS", "FedEx", "DHL"],
            icon: "Users",
          },
          {
            id: "logistics-director",
            title: "Director of Logistics",
            description: "Director overseeing all logistics operations and transportation networks.",
            salaryRange: "$110,000 - $180,000",
            companies: ["Amazon", "UPS", "FedEx", "DHL"],
            icon: "TrendingUp",
          },
          {
            id: "vp-logistics",
            title: "VP of Logistics",
            description: "Executive responsible for global logistics strategy and operations.",
            salaryRange: "$180,000 - $300,000+",
            companies: ["Amazon", "UPS", "FedEx", "DHL"],
            icon: "Award",
          },
        ],
      },
      {
        id: "procurement",
        name: "Procurement Path",
        description: "A career path focused on sourcing and purchasing materials and services.",
        steps: [
          {
            id: "pre-business",
            title: "Pre-Business Courses",
            description: "Complete foundational business courses with focus on operations and supply chain basics.",
            icon: "BookOpen",
          },
          {
            id: "supply-chain-core",
            title: "Supply Chain Core Curriculum",
            description: "Master procurement strategies, supplier management, and contract negotiation.",
            icon: "BookOpen",
          },
          {
            id: "procurement-internship",
            title: "Procurement Internship",
            description: "Intern supporting purchasing activities and supplier management.",
            salaryRange: "$10,000 - $18,000 (Summer)",
            companies: ["Walmart", "Procter & Gamble", "Apple", "Boeing"],
            icon: "Building",
          },
          {
            id: "procurement-specialist",
            title: "Procurement Specialist",
            description: "Entry-level position managing purchase orders and supplier relationships.",
            salaryRange: "$55,000 - $70,000",
            companies: ["Walmart", "Procter & Gamble", "Apple", "Boeing"],
            icon: "ShoppingCart",
          },
          {
            id: "procurement-analyst",
            title: "Procurement Analyst",
            description: "Analyst optimizing purchasing strategies and supplier performance.",
            salaryRange: "$70,000 - $90,000",
            companies: ["Walmart", "Procter & Gamble", "Apple", "Boeing"],
            icon: "Search",
          },
          {
            id: "procurement-manager",
            title: "Procurement Manager",
            description: "Manager responsible for strategic sourcing and supplier relationships.",
            salaryRange: "$90,000 - $120,000",
            companies: ["Walmart", "Procter & Gamble", "Apple", "Boeing"],
            icon: "Users",
          },
          {
            id: "procurement-director",
            title: "Director of Procurement",
            description: "Director overseeing all purchasing activities and sourcing strategies.",
            salaryRange: "$120,000 - $180,000",
            companies: ["Walmart", "Procter & Gamble", "Apple", "Boeing"],
            icon: "TrendingUp",
          },
          {
            id: "chief-procurement",
            title: "Chief Procurement Officer",
            description: "Executive responsible for global procurement strategy and supplier management.",
            salaryRange: "$180,000 - $350,000+",
            companies: ["Walmart", "Procter & Gamble", "Apple", "Boeing"],
            icon: "Award",
          },
        ],
      },
      {
        id: "operations-management",
        name: "Operations Management Path",
        description: "A career path focused on managing production processes and operations.",
        steps: [
          {
            id: "pre-business",
            title: "Pre-Business Courses",
            description: "Complete foundational business courses with focus on operations and supply chain basics.",
            icon: "BookOpen",
          },
          {
            id: "supply-chain-core",
            title: "Supply Chain Core Curriculum",
            description: "Master operations management, process improvement, and quality control.",
            icon: "BookOpen",
          },
          {
            id: "operations-internship",
            title: "Operations Internship",
            description: "Intern supporting production operations and process improvement.",
            salaryRange: "$10,000 - $18,000 (Summer)",
            companies: ["Toyota", "Amazon", "Tesla", "Boeing"],
            icon: "Building",
          },
          {
            id: "operations-coordinator",
            title: "Operations Coordinator",
            description: "Entry-level position supporting daily operations and process execution.",
            salaryRange: "$55,000 - $70,000",
            companies: ["Toyota", "Amazon", "Tesla", "Boeing"],
            icon: "Settings",
          },
          {
            id: "operations-analyst",
            title: "Operations Analyst",
            description: "Analyst optimizing operational processes and performance metrics.",
            salaryRange: "$70,000 - $90,000",
            companies: ["Toyota", "Amazon", "Tesla", "Boeing"],
            icon: "Search",
          },
          {
            id: "operations-manager",
            title: "Operations Manager",
            description: "Manager responsible for production operations and process improvement.",
            salaryRange: "$90,000 - $120,000",
            companies: ["Toyota", "Amazon", "Tesla", "Boeing"],
            icon: "Users",
          },
          {
            id: "operations-director",
            title: "Director of Operations",
            description: "Director overseeing all operational activities and continuous improvement.",
            salaryRange: "$120,000 - $180,000",
            companies: ["Toyota", "Amazon", "Tesla", "Boeing"],
            icon: "TrendingUp",
          },
          {
            id: "chief-operations",
            title: "Chief Operations Officer",
            description: "Executive responsible for global operations strategy and execution.",
            salaryRange: "$180,000 - $400,000+",
            companies: ["Toyota", "Amazon", "Tesla", "Boeing"],
            icon: "Award",
          },
        ],
      },
    ],
  },
  {
    majorId: "experience-design",
    majorName: "Experience Design & Management",
    description: "Explore various career paths in experience design, from event management to hospitality.",
    branches: [
      {
        id: "experience-design",
        name: "Experience Design Path",
        description: "A career path focused on creating memorable customer experiences through thoughtful design.",
        steps: [
          {
            id: "pre-business",
            title: "Pre-Business Courses",
            description: "Complete foundational business courses with focus on design thinking and customer behavior.",
            icon: "BookOpen",
          },
          {
            id: "experience-core",
            title: "Experience Design Core Curriculum",
            description: "Master experience design, customer journey mapping, and service blueprinting.",
            icon: "BookOpen",
          },
          {
            id: "design-internship",
            title: "Experience Design Internship",
            description: "Intern supporting experience design projects and customer research.",
            salaryRange: "$8,000 - $15,000 (Summer)",
            companies: ["Disney", "Airbnb", "Marriott", "IDEO"],
            icon: "Building",
          },
          {
            id: "experience-designer",
            title: "Experience Designer",
            description: "Entry-level position designing customer experiences and touchpoints.",
            salaryRange: "$50,000 - $70,000",
            companies: ["Disney", "Airbnb", "Marriott", "IDEO"],
            icon: "Pen",
          },
          {
            id: "senior-designer",
            title: "Senior Experience Designer",
            description: "Experienced designer leading experience design projects and initiatives.",
            salaryRange: "$70,000 - $95,000",
            companies: ["Disney", "Airbnb", "Marriott", "IDEO"],
            icon: "PenTool",
          },
          {
            id: "design-manager",
            title: "Experience Design Manager",
            description: "Manager responsible for experience strategy and design team leadership.",
            salaryRange: "$95,000 - $130,000",
            companies: ["Disney", "Airbnb", "Marriott", "IDEO"],
            icon: "Users",
          },
          {
            id: "design-director",
            title: "Director of Experience Design",
            description: "Director overseeing all experience design initiatives and customer strategy.",
            salaryRange: "$130,000 - $180,000",
            companies: ["Disney", "Airbnb", "Marriott", "IDEO"],
            icon: "TrendingUp",
          },
          {
            id: "chief-experience",
            title: "Chief Experience Officer",
            description: "Executive responsible for customer experience strategy across the organization.",
            salaryRange: "$180,000 - $350,000+",
            companies: ["Disney", "Airbnb", "Marriott", "IDEO"],
            icon: "Award",
          },
        ],
      },
      {
        id: "event-management",
        name: "Event Management Path",
        description: "A career path focused on planning and executing events that meet client objectives.",
        steps: [
          {
            id: "pre-business",
            title: "Pre-Business Courses",
            description: "Complete foundational business courses with focus on marketing and project management.",
            icon: "BookOpen",
          },
          {
            id: "experience-core",
            title: "Experience Design Core Curriculum",
            description: "Master event planning, project management, and customer experience.",
            icon: "BookOpen",
          },
          {
            id: "event-internship",
            title: "Event Management Internship",
            description: "Intern supporting event planning and execution.",
            salaryRange: "$8,000 - $15,000 (Summer)",
            companies: ["Live Nation", "Marriott", "Event Management Firms", "Corporate Events Teams"],
            icon: "Building",
          },
          {
            id: "event-coordinator",
            title: "Event Coordinator",
            description: "Entry-level position supporting event planning and logistics.",
            salaryRange: "$45,000 - $60,000",
            companies: ["Live Nation", "Marriott", "Event Management Firms", "Corporate Events Teams"],
            icon: "Calendar",
          },
          {
            id: "event-planner",
            title: "Event Planner",
            description: "Planner responsible for designing and executing events.",
            salaryRange: "$60,000 - $85,000",
            companies: ["Live Nation", "Marriott", "Event Management Firms", "Corporate Events Teams"],
            icon: "CheckSquare",
          },
          {
            id: "senior-planner",
            title: "Senior Event Planner",
            description: "Senior planner managing complex events and client relationships.",
            salaryRange: "$85,000 - $110,000",
            companies: ["Live Nation", "Marriott", "Event Management Firms", "Corporate Events Teams"],
            icon: "Users",
          },
          {
            id: "event-director",
            title: "Director of Events",
            description: "Director overseeing all event operations and strategy.",
            salaryRange: "$110,000 - $150,000",
            companies: ["Live Nation", "Marriott", "Event Management Firms", "Corporate Events Teams"],
            icon: "TrendingUp",
          },
          {
            id: "vp-events",
            title: "VP of Events",
            description: "Executive responsible for event strategy and business development.",
            salaryRange: "$150,000 - $250,000+",
            companies: ["Live Nation", "Marriott", "Event Management Firms", "Corporate Events Teams"],
            icon: "Award",
          },
        ],
      },
      {
        id: "hospitality-management",
        name: "Hospitality Management Path",
        description: "A career path focused on managing hotels, resorts, and other hospitality settings.",
        steps: [
          {
            id: "pre-business",
            title: "Pre-Business Courses",
            description: "Complete foundational business courses with focus on service management and operations.",
            icon: "BookOpen",
          },
          {
            id: "experience-core",
            title: "Experience Design Core Curriculum",
            description: "Master hospitality management, service excellence, and guest experience.",
            icon: "BookOpen",
          },
          {
            id: "hospitality-internship",
            title: "Hospitality Management Internship",
            description: "Intern supporting hotel operations and guest services.",
            salaryRange: "$8,000 - $15,000 (Summer)",
            companies: ["Marriott", "Hilton", "Hyatt", "Four Seasons"],
            icon: "Building",
          },
          {
            id: "management-trainee",
            title: "Management Trainee",
            description: "Entry-level position rotating through various hotel departments.",
            salaryRange: "$45,000 - $55,000",
            companies: ["Marriott", "Hilton", "Hyatt", "Four Seasons"],
            icon: "Coffee",
          },
          {
            id: "department-manager",
            title: "Department Manager",
            description: "Manager responsible for a specific hotel department (e.g., front desk, housekeeping).",
            salaryRange: "$55,000 - $75,000",
            companies: ["Marriott", "Hilton", "Hyatt", "Four Seasons"],
            icon: "Users",
          },
          {
            id: "assistant-gm",
            title: "Assistant General Manager",
            description: "Assistant manager supporting overall hotel operations and guest experience.",
            salaryRange: "$75,000 - $100,000",
            companies: ["Marriott", "Hilton", "Hyatt", "Four Seasons"],
            icon: "Star",
          },
          {
            id: "general-manager",
            title: "General Manager",
            description: "Manager responsible for all aspects of hotel operations and performance.",
            salaryRange: "$100,000 - $175,000",
            companies: ["Marriott", "Hilton", "Hyatt", "Four Seasons"],
            icon: "Award",
          },
          {
            id: "regional-director",
            title: "Regional Director",
            description: "Director overseeing multiple properties and regional strategy.",
            salaryRange: "$175,000 - $300,000+",
            companies: ["Marriott", "Hilton", "Hyatt", "Four Seasons"],
            icon: "Globe",
          },
        ],
      },
    ],
  },
]
